version: '3.7'

services:
  seq:
    image: datalust/seq
    ports:
      - "8081:80"
      - "5341:5341"
    environment:
      ACCEPT_EULA: 'Y'
    volumes:
      - ./seq:/data
    restart: unless-stopped
