#!/usr/bin/env php
<?php
declare(strict_types=1);

require_once '../vendor/autoload.php';
const APP_ROOT = __DIR__;

require_once APP_ROOT . '/src/Routes/WebController.php';

use Elephox\Console\ConsoleApplicationBuilder;
use Elephox\Support\Contract\ExceptionHandler;
use Elephox\Web\Commands\ServeCommand;

// Create the custom builder
class ConsoleBuilder extends ConsoleApplicationBuilder {
}

// Build console application
$builder = ConsoleBuilder::create();
$builder->addLogging();

$builder->commands->add(ServeCommand::class);

$app = $builder->build();
try {
	$app->run();
} catch (Throwable $e) {
	$app->services->get(ExceptionHandler::class)->handleException($e);
}
